name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  auto-merge:
    if: |
      github.event.pull_request.base.ref == 'main' &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const isOwner = pr.user.login === 'dikshantsingh510';
            
            // Check for [automerge] keyword
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const hasAutomerge = commits.data.some(c => 
              c.commit.message.includes('[automerge]')
            );
            
            if (!hasAutomerge) return;
            
            console.log(`Auto-merge requested by ${pr.user.login}`);
            
            // Owner: Merge immediately
            if (isOwner) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log('✅ Owner PR auto-merged');
              return;
            }
            
            // Non-owner: Check for approval first
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const approved = reviews.data.some(r => r.state === 'APPROVED');
            
            if (approved) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log('✅ Approved PR auto-merged');
            } else {
              console.log('⏳ Waiting for approval...');
            }